GET https://svlete-sl-func.netlify.app//api/animals/barksalot
###

POST https://svlete-sl-func.netlify.app/api/weather
content-type: application/json

{
    "city": "davao"
}
###
POST https://svlete-sl-func.netlify.app/api/dns
content-type: application/json

{
    "hostname": "www.intel.com"
}
###
POST https://svlete-sl-func.netlify.app/api/topsecret
content-type: application/json

{
    "username": "johndoe",
    "password": "qwerty"
}
###